### ISSUE TITLE
Display issues in other languages

### ISSUE THREAD

**Issue by sswest** [filoper/ms-client#13]
Hello, I successfully compiled the client according to the latest document, but when trying to use other languages, the characters displayed on the client are garbled.

These are my modifications to the client source file:
```c++
Graphics/GraphicsGL.h
-        Char chars[256];
+        Char chars[65535];

Graphics/GraphicsGL.cpp
-    for (uint32_t c = 32; c < 256; c++) {
+    for (uint32_t c = 32; c < 65535; c++) {
 
-    for (uint32_t c = 32; c < 256; c++) {
+    for (uint32_t c = 32; c < 65535; c++) {
```
The server uses HeavenMS and uses UTF-8 encoding:
```Java
src/tools/data/input/GenericLittleEndianAccessor.java
     public final String readAsciiString(int n) {
-        char ret[] = new char[n];
+        byte ret[] = new byte[n];
         for (int x = 0; x < n; x++) {
-            ret[x] = (char) readByte();
+            ret[x] = (byte) readByte();
         }
-        return String.valueOf(ret);
+        try {
+            String str = new String(ret, "UTF-8");
+            return str;
+        } catch (Exception e) {
+            System.err.println(e);
+        }
+        return null;
     }

src/tools/data/output/GenericLittleEndianWriter.java
-    private static Charset ASCII = Charset.forName(MapleLanguageType.LANGUAGE_US.getAscii());
+    private static Charset ASCII = Charset.forName("UTF-8");


src/constants/string/CharsetConstants.java
     public enum MapleLanguageType {
-        LANGUAGE_PT_BR(1, "ISO-8859-1"),
-        LANGUAGE_US(2, "US-ASCII");
+        LANGUAGE_PT_BR(1, "UTF-8"),
+        LANGUAGE_US(2, "UTF-8");
```
When I compile according to the above configuration, all characters appear garbled after entering the game, even if I change other fonts.
<img width="800" alt="3" src="https://user-images.githubusercontent.com/26315209/97680805-3e8fd500-1ad2-11eb-9a4e-578a0b486262.png">

**Comment by filoper** [comment]
Hi!

What language are you trying to use and with which font?

Can you type an example here on how the text should look when not garbled?

When you send a chat message does it appear correct or is it too garbled to read?

Thanks for reporting!

**Comment by sswest** [comment]
> Hi!
> 
> What language are you trying to use and with which font?
> 
> Can you type an example here on how the text should look when not garbled?
> 
> When you send a chat message does it appear correct or is it too garbled to read?
> 
> Thanks for reporting!

Thank you for your reply!

In fact, all the characters are garbled. The screenshots are all English words, but they are not displayed correctly.

I want to use Chinese. These screenshots use the default Roboto font, but even if I use the Areil Unicode MS font, it is garbled.
Enter 123:
<img width="800" alt="123" src="https://user-images.githubusercontent.com/26315209/97706880-5a56a380-1af1-11eb-9bd2-f51a3e7ba795.png">
Game options:
<img width="800" alt="2" src="https://user-images.githubusercontent.com/26315209/97706889-5fb3ee00-1af1-11eb-9e6e-68c91361fbb7.png">
When I restore GraphicsGL.h and GraphicsGL.cpp to their original state, the display is normal:
<img width="800" alt="4" src="https://user-images.githubusercontent.com/26315209/97706901-65113880-1af1-11eb-86c0-e193932cfbd7.png">
Finally, when I changed the resolution of the game, a new problem appeared.
<img width="800" alt="3" src="https://user-images.githubusercontent.com/26315209/97706910-693d5600-1af1-11eb-9733-fb57ee00a4c0.png">

**Comment by filoper** [comment]
Did you update the font paths in the generated Settings file?
It has these two fields that you should update: FontPathNormal and FontPathBold

When I tested with Chinese myself, I used this font [https://fonts.google.com/specimen/Noto+Serif+SC?subset=chinese-simplified](https://fonts.google.com/specimen/Noto+Serif+SC?subset=chinese-simplified)

I do however believe there was a problem for some font size which didn't display correctly, but changing parameter here could workaround it:

https://github.com/filoper/ms-client/blob/ce8a44ecc94e6ab320d43f232b2e08df2b835b14/Graphics/GraphicsGL.cpp#L214-L221
